#!/usr/bin/python
#-*coding:utf-8-*-
#Filename:auto_springside_mvc.py
#Author:zhc
import os
import sys
from string import Template
def getXaX(s):
    r=''
    ss=s.split('_')
    for t in ss:
        r+=t.capitalize()
    return r

def getxaX(s):
    r=''
    ss=s.split('_')
    for i,t in enumerate(ss):
        if i==0:
            r+=t
        else:
            r+=t.capitalize()
    return r

def getType(s,columnDict):
    r=''
    s=s.lower()
    for k in columnDict:
        l=len(k)
        v=s[:l]
        if v==k:
            r=columnDict[k]
            break
    return r
def saveFile(path,fileName,value):
    if os.path.isdir(path)==False:
        com='''mkdir -p %s''' %path
        if os.name=='nt':
            com='''md %s''' %path
        
        os.system(com)
    #os.mkdir('%s/sql/mysql' %(self.savePath))
    #指定当前工作目录
    os.chdir(path)
    #创建sql文件
    fobj=open(fileName, mode='w')
    fobj.write(value)
    fobj.close()
    #获得当前工作目录
    cwd=os.getcwd()
    print os.listdir(cwd)      
        
class Project(object):
    #设置全局变量
    """version 0.1"""
    #项目包名com.xxxx
    groupId='com.zhc'
    #项目名
    artifactId='zhc'
    #数据表名
    tableNames=[] #[表名，id名]
    #数据表字段字典
    tableNameDict={} #表明：[[列名,类型]，[列名,类型]]
    
    #数据库映射表字段
    columnDict={'bigint':'Long','varchar':'String','timestamp':'Date','int':'int','text':'String','longtext':'String'}
    
    #完整建表语句
    #createSql=''
    #保存路径
    savePath=''
    #收集变量方法
    def setGroupId(self):
        pLName=raw_input('groupId (com.zhc):')
        if pLName!='':
           self.groupId=pLName
           
    def setArtifactId(self):
        pRName=raw_input('artifactId (zhc):')
        if pRName!='':
            self.artifactId=pRName
    
    def setTableName(self):
        tName=raw_input('tableName (not empty):')
        if tName!='':
            tid=raw_input('tableId (id):')
            if tid=='':
                tid='id'
            self.tableNames+=[[tName,tid]]
            self.setTableName()
             
    def setTableDic(self):
        for t in self.tableNames:
            print "Enter %s table's column(xxx_xxx)"  %(t)
            tDict=[]
            self.setColumnName(tDict)
            self.tableNameDict[t[0]]=tDict
        print '%s' %self.tableNameDict
          
    def setColumnName(self,cName):
        tName=raw_input('columnName (not empty):')
        if tName!='':
            tType=raw_input('columnType (varchar(255)):')
            if tType=='':
                tType='varchar(255)'
            cName+=[[tName,tType]]
            self.setColumnName(cName)     
            
    def setSavePath(self):
        path=raw_input('savePath (.):')
        if path=='':
            self.savePath=os.getcwd()
        else:
            self.savePath=path               
                
            
    def __init__(self):
        self.setGroupId()
        self.setArtifactId()
        self.setTableName()
        self.setTableDic()
        self.setSavePath()
        print 'LName:%s ,RName:%s,TName:%s' \
             %(self.groupId,self.artifactId,self.tableNames) 
            
        
    #创建sql(mysql)
    def saveMySql(self):
        print '*** creat mysql'
        dSql='drop table if exists %s_%s;\n'
        cSql='create table %s_%s ( %s )engine=InnoDB DEFAULT CHARSET=utf8;\n'
        createSql=''
        #循环表
        for t in self.tableNames:
            sql=dSql %(self.artifactId,t[0])
            #id为主键
            ccSql='%s bigint auto_increment,' %(t[1])
            #循环列
            for c in self.tableNameDict[t[0]]:
                ccSql+='%s %s ,' %(c[0],c[1])
            ccSql+='primary key ('+t[1]+')' 
            sql+=cSql %(self.artifactId,t[0],ccSql)
            #把完整sql语句保存
            createSql+=sql
        #保存路径
        path='%s\\sql\\mysql' %(self.savePath)
        saveFile(path, 'schema.sql', createSql)
        
    #创建sql(h2)
    def saveH2Sql(self):
        print '*** creat H2Sql'
        dSql='drop table if exists %s_%s;\n'
        cSql='create table %s_%s ( %s );\n'
        createSql=''
        #循环表
        for t in self.tableNames:
            sql=dSql %(self.artifactId,t[0])
            #id为主键	
            ccSql='%s bigint generated by default as identity,' %(t[1])
            #循环列
            for c in self.tableNameDict[t[0]]:
                ccSql+='%s %s ,' %(c[0],c[1])
            ccSql+='primary key ('+t[1]+')' 
            sql+=cSql %(self.artifactId,t[0],ccSql)
            #把完整sql语句保存
            createSql+=sql
        #保存路径
        path='%s\\sql\\h2' %(self.savePath)
        saveFile(path, 'schema.sql', createSql)        
    
    #创建entity
    def saveEntity(self):
        print '*** create entity'
        str=Template('''
        package ${groupId}.${artifactId}.entity;
        import java.util.Date;
        import java.util.Map;
        import java.util.TreeMap;
        import javax.persistence.Column;
        import javax.persistence.Entity;
        import javax.persistence.JoinColumn;
        import javax.persistence.Table;
        import org.apache.commons.lang3.builder.ToStringBuilder;
        import com.fasterxml.jackson.annotation.JsonFormat;
        import org.springframework.data.annotation.Id;
        import javax.persistence.GeneratedValue;
        import javax.persistence.GenerationType;
        
        @Entity
        @Table(name = "${artifactId}_${tableName}")
        public class ${tableNameU} extends ${idU}Entity{
        public ${tableNameU}(){
		
	}
	
        
        ${other}
        
	${init}      
        
	public void init(String body){
		String[] bodys=body.split("&");
		Map<String,Object> map=new TreeMap<String, Object>();
		for(String s:bodys){
			String[] ss=s.split("=");
			if(ss.length>1){
				map.put(ss[0], ss[1]);
			}else{
				
				map.put(ss[0], "");
			}
			
		}
		this.init(map);
	}        
        
        @Override
	public String toString() {
	return ToStringBuilder.reflectionToString(this);
	}
        }
        ''')
        
        other=Template('''
        protected ${type} ${name};
        
        ${JsonFormat}
        @Column(name="${name_}")
	public ${type} get${nameU}() {
		return ${name};
	}

	public void set${nameU}(${type} ${name}) {
		this.${name} = ${name};
	}
        
        ''')
        idEntity=Template('''
        package ${groupId}.${artifactId}.entity;
        import javax.persistence.GeneratedValue;
        import javax.persistence.GenerationType;
        import javax.persistence.Id;
        import javax.persistence.Column;
        import javax.persistence.MappedSuperclass;
        
        // JPA 基类的标识
        @MappedSuperclass
        public abstract class ${idU}Entity {
        
        protected Long ${id};

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
        @Column(name="${id_}")
	public Long get${idU}() {
		return ${id};
	}

	public void set${idU}(Long ${id}) {
		this.${id} = ${id};
	}
}
        ''')
        #循环表
        for t in self.tableNames:
            r=''
            ot=''
            initF=Template('''
            public void init(Map<String,Object> map) {
            for (String key : map.keySet()) {
                    
                   ${initVale}

            }
            }''')  
            initV=''
            #拼写other
            #循环列
            for c in self.tableNameDict[t[0]]:
                inits=Template('''
                if(key=="${name}"){
                    ${name}=(${type})map.get(${name});
                    continue;
		}
                ''')
                initV+=inits.substitute(name=getxaX(c[0]),type=getType(c[1],self.columnDict))
                jf='@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")'
                if getType(c[1],self.columnDict)!='Date':
                    jf=''
                ot+=other.substitute(type=getType(c[1],self.columnDict),name=getxaX(c[0]),name_=c[0],nameU=getXaX(c[0]),JsonFormat=jf)
            r+=str.substitute(groupId=self.groupId,artifactId=self.artifactId,tableName=t[0],\
                              tableNameU=getXaX(t[0]),id=getxaX(t[1]),idU=getXaX(t[1]),id_=t[1],other=ot,init=initF.substitute(initVale=initV))  
            saveFile('%s\\entity' %(self.savePath), getXaX(t[0])+'.java', r)
            #保存主键基类
            idr=idEntity.substitute(groupId=self.groupId,artifactId=self.artifactId,tableName=t[0],\
                                    id=getxaX(t[1]),idU=getXaX(t[1]),id_=t[1])
            saveFile('%s\\entity' %(self.savePath), getXaX(t[1])+'Entity.java', idr)
            
    #创建repository（DAO）
    def saveRepository(self):
        print '*** create repository'
        str=Template('''
        package ${groupId}.${artifactId}.repository;
        import org.springframework.data.domain.Page;
        import org.springframework.data.domain.Pageable;
        import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
        import org.springframework.data.jpa.repository.Modifying;
        import org.springframework.data.jpa.repository.Query;
        import org.springframework.data.repository.PagingAndSortingRepository;
        import ${groupId}.${artifactId}.entity.${tableNameU};
        public interface ${tableNameU}Dao extends PagingAndSortingRepository<${tableNameU}, Long>, JpaSpecificationExecutor<${tableNameU}> {

        }
        ''')
        #循环表
        for t in self.tableNames:
            r=str.substitute(groupId=self.groupId,artifactId=self.artifactId,tableNameU=getXaX(t[0]))  
            saveFile('%s\\repository' %(self.savePath), getXaX(t[0])+'Dao.java', r)
    #创建service
    def saveService(self):
        print 'create service'
        strbase=Template('''
        package ${groupId}.${artifactId}.service;
        import java.util.List;
        import org.springframework.beans.factory.annotation.Autowired;
        import org.springframework.data.repository.PagingAndSortingRepository;
        import org.springframework.stereotype.Component;
        import org.springframework.transaction.annotation.Transactional;
        
        @Component
        @Transactional
        public abstract class ServiceBase<Entity,Dao extends PagingAndSortingRepository<Entity, Long>> {
	@Autowired
	private Dao dao;
	public Entity getEntity(Long id){
		return dao.findOne(id);
	}
	
	public Entity saveEntity(Entity entity) {
		return dao.save(entity);
		
	}
	
	public void deleteEntity(Long id) {
		dao.delete(id);
	}
	
	public List<Entity> getAllEntity() {
		return (List<Entity>) dao.findAll();
	}
        }

        ''')
        #保存泛型
        saveFile('%s\\service' %(self.savePath), 'ServiceBase.java', strbase.substitute(groupId=self.groupId,artifactId=self.artifactId))    
        str=Template('''
        package ${groupId}.${artifactId}.service.${tableName};
        import java.util.List;
        import java.util.Map;
        import org.springframework.beans.factory.annotation.Autowired;
        import org.springframework.data.domain.Page;
        import org.springframework.data.domain.PageRequest;
        import org.springframework.data.domain.Sort;
        import org.springframework.data.domain.Sort.Direction;
        import org.springframework.data.jpa.domain.Specification;
        import org.springframework.stereotype.Component;
        import org.springframework.transaction.annotation.Transactional;
        import ${groupId}.${artifactId}.entity.${tableNameU};
        import ${groupId}.${artifactId}.repository.${tableNameU}Dao;
        import org.springside.modules.persistence.DynamicSpecifications;
        import org.springside.modules.persistence.SearchFilter;
        import org.springside.modules.persistence.SearchFilter.Operator;
        import ${groupId}.${artifactId}.service.ServiceBase;
        // Spring Bean的标识.
        @Component
        // 类中所有public函数都纳入事务管理的标识.
        @Transactional
        public class ${tableNameU}Service extends ServiceBase<${tableNameU}, ${tableNameU}Dao> {
        
        }''')
        #循环表
        for t in self.tableNames:
            r=str.substitute(groupId=self.groupId,artifactId=self.artifactId,\
                             tableNameU=getXaX(t[0]),tableName=getxaX(t[0]),id=getxaX(t[1]))  
            saveFile('%s\\service\\%s' %(self.savePath,getxaX(t[0])), getXaX(t[0])+'Service.java', r)        
    #创建restful
    def saveRestful(self):
        print '***create restul'
        str=Template('''
        package ${groupId}.${artifactId}.rest;
        import java.net.URI;
        import java.util.List;
        import javax.validation.Validator;
        import org.slf4j.Logger;
        import org.slf4j.LoggerFactory;
        import org.springframework.beans.factory.annotation.Autowired;
        import org.springframework.http.HttpHeaders;
        import org.springframework.http.HttpStatus;
        import org.springframework.http.ResponseEntity;
        import org.springframework.web.bind.annotation.PathVariable;
        import org.springframework.web.bind.annotation.RequestBody;
        import org.springframework.web.bind.annotation.RequestMapping;
        import org.springframework.web.bind.annotation.RequestMethod;
        import org.springframework.web.bind.annotation.ResponseStatus;
        import org.springframework.web.bind.annotation.RestController;
        import org.springframework.web.util.UriComponentsBuilder;
        import ${groupId}.${artifactId}.entity.${tableNameU};
        import ${groupId}.${artifactId}.service.${tableName}.${tableNameU}Service;
        import org.springside.modules.web.MediaTypes;
        import java.util.Map;
        import java.util.TreeMap;
        
        @RestController
        @RequestMapping(value = "/api/v1/${tableName}")
        public class ${tableNameU}RestController {

	private static Logger logger = LoggerFactory.getLogger(${tableNameU}RestController.class);

	@Autowired
	private ${tableNameU}Service ${tableName}Service;

	@RequestMapping(method = RequestMethod.GET, produces = MediaTypes.JSON_UTF_8)
	public List<${tableNameU}> list() {
		return ${tableName}Service.getAllEntity();
	}

	@RequestMapping(value = "/{id}", method = RequestMethod.GET, produces = MediaTypes.JSON_UTF_8)
	public ${tableNameU} get(@PathVariable("id") Long id) {
		${tableNameU} ${tableName} = ${tableName}Service.getEntity(id);
		if (${tableName} == null) {
                        String message="NOT FIND";
			throw new RestException(HttpStatus.NOT_FOUND, message);
		}
		return ${tableName};
	}

	@RequestMapping(method = RequestMethod.POST, consumes = MediaTypes.JSON)
	public ResponseEntity<?> create(@RequestBody String body, UriComponentsBuilder uriBuilder) {
                ${tableNameU} ${tableName}=new ${tableNameU}();
                ${tableName}.init(body);
		// 保存
		${tableName}Service.saveEntity(${tableName});

	        // 按照Restful风格约定，创建指向新任务的url, 也可以直接返回id或对象.
		Long id = ${tableName}.get${idU}();
		URI uri = uriBuilder.path("/api/v1/${tableName}/" + id).build().toUri();
		HttpHeaders headers = new HttpHeaders();
		headers.setLocation(uri);

		return new ResponseEntity(headers, HttpStatus.CREATED);
	}

	@RequestMapping(value = "/{id}", method = RequestMethod.PUT, consumes = MediaTypes.JSON)
	// 按Restful风格约定，返回204状态码, 无内容. 也可以返回200状态码.
	@ResponseStatus(HttpStatus.NO_CONTENT)
	public void update(@RequestBody String body) {
                ${tableNameU} ${tableName}=new ${tableNameU}();
                ${tableName}.init(body);
		// 保存
		${tableName}Service.saveEntity(${tableName});
             
	}

	@RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
	@ResponseStatus(HttpStatus.NO_CONTENT)
	public void delete(@PathVariable("id") Long id) {
		${tableName}Service.deleteEntity(id);
	}
        }
        ''')
        #循环表
        for t in self.tableNames:
            r=str.substitute(groupId=self.groupId,artifactId=self.artifactId,\
                             tableNameU=getXaX(t[0]),tableName=getxaX(t[0]),id=getxaX(t[1]),idU=getXaX(t[1]))
            saveFile('%s\\rest' %(self.savePath), getXaX(t[0])+'RestController.java', r)                
#执行
def _main_():
    project =Project()
    project.saveMySql()
    project.saveH2Sql()
    project.saveEntity()
    project.saveRepository()
    project.saveService()
    project.saveRestful()
    
_main_()